config/routes.rb
Rails.application.routes.draw do
  resources :ride_later_requests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ride_later_request.rb
class RideLaterRequest < ApplicationRecord
  enum status:{
    UnderConstruction:1,
    Submitted: 2,
    Unfulfilled:3,
    QuotesReady:4,
    Fulfilled: 5,
    Rejected:6,
    Ignored:7,
    Cancelled:8,
    Expired:9
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ride_later_requests_controller.rb
class RideLaterRequestsController < ApplicationController
  before_action :set_ride_later_request, only: [:show, :edit, :update, :destroy]

  # GET /ride_later_requests
  # GET /ride_later_requests.json
  def index
    @ride_later_requests = RideLaterRequest.all
  end

  # GET /ride_later_requests/1
  # GET /ride_later_requests/1.json
  def show
  end

  # GET /ride_later_requests/new
  def new
    @ride_later_request = RideLaterRequest.new
  end

  # GET /ride_later_requests/1/edit
  def edit
  end

  # POST /ride_later_requests
  # POST /ride_later_requests.json
  def create
    @ride_later_request = RideLaterRequest.new(ride_later_request_params)

    respond_to do |format|
      if @ride_later_request.save
        format.html { redirect_to @ride_later_request, notice: 'Ride later request was successfully created.' }
        format.json { render :show, status: :created, location: @ride_later_request }
      else
        format.html { render :new }
        format.json { render json: @ride_later_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ride_later_requests/1
  # PATCH/PUT /ride_later_requests/1.json
  def update
    respond_to do |format|
      if @ride_later_request.update(ride_later_request_params)
        format.html { redirect_to @ride_later_request, notice: 'Ride later request was successfully updated.' }
        format.json { render :show, status: :ok, location: @ride_later_request }
      else
        format.html { render :edit }
        format.json { render json: @ride_later_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ride_later_requests/1
  # DELETE /ride_later_requests/1.json
  def destroy
    @ride_later_request.destroy
    respond_to do |format|
      format.html { redirect_to ride_later_requests_url, notice: 'Ride later request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride_later_request
      @ride_later_request = RideLaterRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ride_later_request_params
      params.require(:ride_later_request).permit(:customer_name, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ride_later_requests_helper.rb
module RideLaterRequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ride_later_requests/_form.html.erb
<%= form_with(model: ride_later_request, local: true) do |form| %>
  <% if ride_later_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ride_later_request.errors.count, "error") %> prohibited this ride_later_request from being saved:</h2>

      <ul>
      <% ride_later_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name, id: :ride_later_request_customer_name %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status, id: :ride_later_request_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ride_later_requests/edit.html.erb
<h1>Editing Ride Later Request</h1>

<%= render 'form', ride_later_request: @ride_later_request %>

<%= link_to 'Show', @ride_later_request %> |
<%= link_to 'Back', ride_later_requests_path %>

app/views/ride_later_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ride Later Requests</h1>

<table>
  <thead>
    <tr>
      <th>Customer name</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ride_later_requests.each do |ride_later_request| %>
      <tr>
        <td><%= ride_later_request.customer_name %></td>
        <td><%= ride_later_request.status %></td>
        <td><%= link_to 'Show', ride_later_request %></td>
        <td><%= link_to 'Edit', edit_ride_later_request_path(ride_later_request) %></td>
        <td><%= link_to 'Destroy', ride_later_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ride Later Request', new_ride_later_request_path %>

app/views/ride_later_requests/new.html.erb
<h1>New Ride Later Request</h1>

<%= render 'form', ride_later_request: @ride_later_request %>

<%= link_to 'Back', ride_later_requests_path %>

app/views/ride_later_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer name:</strong>
  <%= @ride_later_request.customer_name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ride_later_request.status %>
</p>

<%= link_to 'Edit', edit_ride_later_request_path(@ride_later_request) %> |
<%= link_to 'Back', ride_later_requests_path %>